"""Add new column

Revision ID: 84f442ba0317
Revises: 
Create Date: 2024-06-25 21:31:59.611940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84f442ba0317'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Advertisement', 'photos_link',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('id_UNIQUE', table_name='Advertisement')
    op.create_foreign_key(None, 'Advertisement', 'User', ['owner_telegram_id'], ['telegram_id'])
    op.drop_index('fk_Answer_1_idx', table_name='Answer')
    op.drop_index('lot_idx', table_name='Question')
    op.drop_constraint('lot', 'Question', type_='foreignkey')
    op.create_foreign_key(None, 'Question', 'Lot', ['lot_id'], ['id'])
    op.drop_index('user_adv_token_UNIQUE', table_name='User')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_adv_token_UNIQUE', 'User', ['user_adv_token'], unique=True)
    op.drop_constraint(None, 'Question', type_='foreignkey')
    op.create_foreign_key('lot', 'Question', 'Lot', ['lot_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_index('lot_idx', 'Question', ['lot_id'], unique=False)
    op.create_index('fk_Answer_1_idx', 'Answer', ['lot_id'], unique=False)
    op.drop_constraint(None, 'Advertisement', type_='foreignkey')
    op.create_index('id_UNIQUE', 'Advertisement', ['id'], unique=True)
    op.alter_column('Advertisement', 'photos_link',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    # ### end Alembic commands ###
